### ISSUE TITLE
Looks like raw_seqs retrieved (-e) is different when -x, and -t and -o are used.

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidator#106]
Not sure if I have made a mistake, or this is indeed the case. I was working with 'swissprot -remote'.

**Comment by IsmailM** [comment]
That's interesting because they both run the same method `GeneValidator::RawSequences.run` 

- `-e` Runs `RawSequences.run` [here](https://github.com/wurmlab/genevalidator/blob/master/bin/genevalidator#L131).
- Normal raw_seq extraction runs `RawSequences.run` [here](https://github.com/wurmlab/genevalidator/blob/master/lib/genevalidator.rb#L77).

This [method](https://github.com/wurmlab/genevalidator/blob/master/lib/genevalidator/get_raw_sequences.rb#L31) extracts raw_seqs based on accession number so you should get the same raw_sequences...

Any chance you could send me an exemplar input file and the commands that you ran.

**Comment by yeban** [comment]
Would be great if you could look into this. Thanks. I was using the test XML and TSV file from data/ against swissprot -remote. Used gv's -e option to extract the raw sequences.

**Comment by IsmailM** [comment]
Quick Question…

Did you create both the XML and the TSV yourself using the same parameters?

(GeneValidator uses a [E-value of 1e-5](https://github.com/wurmlab/genevalidator/blob/master/lib/genevalidator/blast.rb#L17) when generating blast XML files)

**Comment by yeban** [comment]
I used the XML file generated by GV, but generated the TSV file myself - didn't specify e-value cut-off, which probably is the reason raw_seq files are different.

**Comment by IsmailM** [comment]
I’ll document this in the Readme…

**Comment by IsmailM** [comment]
E-Value used by GeneValidator in BLAST is now documented in the README (see 4ef6aff)
