### ISSUE TITLE
Unable to resolve dependencies: statsample requires spreadsheet (~> 1.0.3); daru requires spreadsheet (~> 1.1.1)

### ISSUE THREAD

**Issue by sujaikumar** [wurmlab/genevalidator#115]
The web app version looks/works great - thanks! :-) Looking forward to running it on the command line.

However, I get this error when I ran `sudo gem install genevalidator`

    ERROR:  While executing gem ... (Gem::DependencyError)
        Unable to resolve dependencies: statsample requires spreadsheet (~> 1.0.3); daru requires spreadsheet (~> 1.1.1)

These are the preparatory steps I did on a brand new ubuntu 14.04 VM (all these completed successfully):

    sudo apt-get update
    sudo apt-get -y upgrade
    sudo apt-get install -y ruby2.0 ruby2.0-dev make g++

    curl ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.3.0+-x64-linux.tar.gz | tar xzf -

    curl http://mafft.cbrc.jp/alignment/software/mafft-7.294-without-extensions-src.tgz | tar xzf -
    cd mafft-7.294-without-extensions/core
    make install PREFIX=/home/ubuntu/mafft-7.294-without-extensions

    export PATH=$HOME/ncbi-blast-2.3.0+/bin/:$HOME/mafft-7.294-without-extensions/bin:$HOME/mafft-7.294-without-extensions/binaries:$PATH

    mkdir blastdb
    curl ftp://ftp.ebi.ac.uk/pub/databases/uniprot/knowledgebase/uniprot_sprot.fasta.gz | zcat >blastdb/uniprot_sprot.20160518.fasta
    makeblastdb -dbtype prot -in blastdb/uniprot_sprot.20160518.fasta -parse_seqids

**Comment by IsmailM** [comment]
Hey @sajalkumar,

Sorry about the delay in getting back to you, I’ve been out of the office recently.

Yep that’s an ‘[bug](https://bugs.launchpad.net/ubuntu/+source/ruby2.0/+bug/1310292)’ in Ubuntu Trusty that has been fixed in Utopic. Basically running ‘apt-get install ruby2.0’ in Trusty does not update the default ruby but rather installs ruby as `ruby2.0`. As such the default ruby would as such still be ruby 1.9.3 (which is not supported with GeneValidator).

I would personally suggest installing the ruby 2.3.0 using [RVM](https://rvm.io/rvm/install) or [chruby](https://github.com/postmodern/chruby). You can install ruby as follows using RVM:

```bash
$ curl -sSL https://get.rvm.io | bash -s stable --ruby
$ source ~/.rvm/scripts/rvm
$ rvm use ruby
```
