### ISSUE TITLE
Multi-threaded Validations

### ISSUE THREAD

**Issue by manu-tej** [wurmlab/genevalidator#148]
I don't see the validations running parallelly even after I specify the --num_threads argument. Am I doing anything wrong?

**Comment by IsmailM** [comment]
Hi @manu-tej,

With the `--num_threads` argument, the validations themselves are not run in parallel, but rather individual sequences are analysed in parallel.

I hope this answers your question? If you feel that your analyses are still not running in parallel, please feel free to provide more details here so that we can help you debug this.

Kind Regards, 
Ismail Moghul

**Comment by IsmailM** [comment]
Feel free to reopen if this is a still an issue
