### ISSUE TITLE
Run validations multithreaded.

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidator#65]
I see `Validation#new` takes an argument to enable multithreading, but can't find how to enable multithreading from the command line.

**Comment by yeban** [comment]
Similarly, the option to pass `raw_sequences` seems to have gone.

**Comment by IsmailM** [comment]
At the moment the multi-threading is all over the place...

In the Alpha branch, I have removed the `multi-threading` argument on `Validation#new`. Rather, I turn on multi-threading if more than one thread is provided (i.e. through the `-num_threads` CLI option). I think this makes a lot more sense.

It will be some time before I merge these changes with the master - I need to fully test these changes...

The initial problem was that when running a high number of sequences with GeneValidator (i.e. something in the order of a few 10,000s), you would get a Thread Error half way through... (This problem also occurs when using original GV source code from last August - i.e. from before I made any changes to GV). 

After some searching, I found out the reason was that the current method of multi-threading was not thread safe (see [here](https://github.com/monicadragan/GeneValidator/blob/master/lib/genevalidator.rb#L256)) i.e. loads of threads were created at once (threads that did not physically exist), causing the Thread Error...

Thus, I'm now using the thread safe `Queue.new` in the alpha branch (see [here](https://github.com/monicadragan/GeneValidator/blob/alpha/lib/genevalidator.rb#L272)), to store all the work units and then create threads for each work-unit (while ensuring that the maximum number of threads at any moment is equal to the number of threads provided).

**Comment by yeban** [comment]
In the current approach it looks like a new thread is spawned for each query sequence. Which would mean as many threads as the number of query sequences. No doubt it crashes when there are too many queries. On Mac, a process is not allowed to launch more than 2048 threads. Though I don't know what happens if you try to launch a 2049th thread.

Using `--num_threads` is a good idea. Though, I don't see the need to handle the case for 1 thread (`--num_threads` not set) and more than 1 threads separately.

Your `run_multithreaded_validation` looks like it will work. Consider using a "proper" thread pool for cleaner code and so you won't have to wait till all `work_unit`s are queued up. You can re-use the same thread pool for other work as well (for example, if if getting raw sequences can be parallelised). Here's a nice, simplest possible thread pool implementation I have found - http://burgestrand.se/code/ruby-thread-pool/ (you can pull the source from [here](https://github.com/yeban/sequenceserver/blob/6a4d38ec88a75f49dd03fa9dff0c463f4c386633/lib/sequenceserver/pool.rb)).

**Comment by yeban** [comment]
`ThreadError` issue may bite me today. I have a GV job running on ~14000 sequences. If it crashes after, say 8000 sequences, will I still be able to view the report for those 8000? Is GV able to resume after crash / kill?

**Comment by IsmailM** [comment]
Thanks for that link - looks quite useful...

GV is currently unable to resume after a crash/kill... However, it will have created the output for however many sequences analysed...

If you used the Gem version of GV, it is likely to produce a TreadError (or perhaps not - I sometime managed to get 18,000s of sequences analysed before seeing the Thread Error).

If you used the master branch, I have temporarily turned off Multi-threading 

If you used the alpha branch, it should just work (in theory) - It has worked the few times I've run it, but I haven't fully tested it out yet... 

Also look at #67

**Comment by yeban** [comment]
I used the gem version, but used the following script to run GV to set `raw_sequences` and enable multi-threading :/

```
#!/usr/bin/env ruby

require 'genevalidator'

puts 'Starting ...'
GeneValidator::Validation.new({
  input_fasta_file: '...',
  blast_xml_file: '...',
  raw_sequences: '...',
  db: '...', # https://github.com/monicadragan/GeneValidator/issues/66
  multithreaded: true,
  validations: ['all']
}).run
puts '... done.'
```

**Comment by yannickwurm** [comment]
So can biologists now once again run GV without ti crashing on a real dataset?  thanks

**Comment by IsmailM** [comment]
Multi-threading is not really ready yet... 

In theory, it is kind of ready (available on the alpha branch), but I will need to take another look and test it fully with large real datasets (i.e. 40k+ sequences)...

The current master will let you run GV on large real dataset, but you are forced to use a single thread.

You can use @yeban's method with the current master to above to override this or use an older version - but GV is likely to crash (ThreadError) once you reach something like 10-16k sequences...

**Comment by yannickwurm** [comment]
@yeban can you review @ismailm's current alpha approach?  This is indeed a major issue that needs to be addressed prior to submission.

**Comment by IsmailM** [comment]
@yannickwurm 

@yeban has already reviewed the current alpha approach and has suggested an alternative:

This is from a comment above: 

>Your run_multithreaded_validation looks like it will work. Consider using a "proper" thread pool for cleaner code and so you won't have to wait till all work_units are queued up. You can re-use the same thread pool for other work as well (for example, if if getting raw sequences can be parallelised). Here's a nice, simplest possible thread pool implementation I have found - http://burgestrand.se/code/ruby-thread-pool/ (you can pull the source from [here](https://github.com/yeban/sequenceserver/blob/6a4d38ec88a75f49dd03fa9dff0c463f4c386633/lib/sequenceserver/pool.rb)).

Thus I plan to implement this to:
- multithread the actual validations 
- multithread the get_raw_sequence command (so that multiple sequences can be obtained from the db at the same time...
