### ISSUE TITLE
JS stuff

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidator#76]
Few things that stood out at a quick glance through the JS code:
- [ ] All functions are global. Not good.
- [x] `use strict` should be declared once per file, globally, and not in selected functions (why?)
- [x] `showAllPlots` and `hideAllPlots` change `window.onclick`'s value. This will throw optimising JS VMs off track, especially JITs. Not very logical either, imo.
- [x] "Sorry, this feature is not supported in your browser" is a very unhelpful error message. Tell them why, or what they can do (which browser to use).
- [x] `showAllPlots` calls `remove_all_plots()` before drawing all plots. Means if I had already opened plots for 30 hits, it throws away those and redraws them? Wasteful?
- ~~ You can probably use Bootstraps button plugin (included by default) to change 'show/hide' status.~~
- ~~Similarly, checkbox styled as button could be used for toggle buttons and work with checkboxes' `checked` state. Bootstrap has something to help with this (they also have togglable buttons without using checkboxes I think - which helps to provide visual feedback)~~
- [ ] browser detection is done twice

**Comment by IsmailM** [comment]
>- All functions are global. Not good.

I haven't heard of global/local functions. Can you explain further...
 
>- `use strict` should be declared once per file, globally, and not in selected functions (why?)

JSHINT suggests 'Use the function form of "use strict".' I believe this is so that it prevents problems when concatenating scripts that aren't strict. Nevertheless, I have changed this in #94. 

>- `showAllPlots` and `hideAllPlots` change `window.onclick`'s value. This will throw optimising JS VMs off track, especially JITs. Not very logical either, imo.

Fixed in #94

>- "Sorry, this feature is not supported in your browser" is a very unhelpful error message. Tell them why, or what they can do (which browser to use).

Fixed in #94

>- `showAllPlots` calls `remove_all_plots()` before drawing all plots. Means if I had already opened plots for 30 hits, it throws away those and redraws them? Wasteful?

Fixed in #94

>- You can probably use Bootstraps button plugin (included by default) to change 'show/hide' status.
>- Similarly, checkbox styled as button could be used for toggle buttons and work with checkboxes' `checked` state. Bootstrap has something to help with this (they also have togglable buttons without using checkboxes I think - which helps to provide visual feedback)

I tried doing this - but it turned out to be quite some work - Bootstrap button plugin only works when you have the `btn` class, which effects how things look... It was much easier to use the current `.status` implementation...

>- browser detection is done twice

This is a feature... Basically the Chrome Modal is a dismissible modal that is shown on load and whenever running a feature that cannot be run in chrome... Thus, you can still see the table of results in chrome and all features (creating plots etc.) that cannot be run in chrome are elegantly handed ...

**Comment by yeban** [comment]
Look up the module pattern and namespace patterns in JS. For example here - http://addyosmani.com/resources/essentialjsdesignpatterns/book/#modulepatternjavascript. And it's generally at the top of each module that you add `use strict`. At the moment, global `use strict` is fine.

Bootstrap was just an idea. I wanted to make sure you had considered and rejected it.

A typical way to structure code that depends on browser detection is to re-define the function on first invocation:

```
function sayHi() {
  if (isChrome() {
   function sayHi () { # won't do anything in chrome }
  }
  else {
   function sayHi () { alert('Hi, all') }
}
```

I think raised this point because `addData` calls out to `checkIfUsingChromeLocally` the first thing, and it's not like the browser will change while user is viewing the report ...

**Comment by yeban** [comment]
updated the list
